export {default as CompanyForm } from './CompanyForm'
export {default as Credentails } from './Credentails'
export {default as InstitutionForm } from './InstitutionForm'
export {default as StudentForm } from './StudentForm'
export {default as Option } from './Option'
export {default as Header } from './Header'
export {default as UserForm} from './DynamicForm'